# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b649da114fd70dc7c4569dc4775d38a19adb8c69fa7d545750b47f64750e1e9245d8289a1d2ab7ff243dcc94d2364b58db3cc6d8fabbe4b9422126169bb75da

test:
  secret_key_base: 059631995eda3f9607657553e95f5d094771cb8057d39cf3153c83f34edacbb8f6457821ad3747dcbfecad0eb9f9a8aea9b78db758cd2885144284168ef5d53e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
